[project]
name = "uit-docs-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langgraph-cli[inmem]>=0.4.4",
    "psycopg2-binary>=2.9.11",
]
