[project]
name = "uit-docs-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.119.1",
    "langchain-openai>=1.0.0",
    "langgraph>=1.0.0",
    "langgraph-api>=0.4.47",
    "langgraph-cli[inmem]>=0.4.4",
    "lightrag-hku[api]",
    "mineru[core]>=2.6.2",
    "nltk>=3.9.2",
    "psycopg2-binary>=2.9.11",
    "python-multipart>=0.0.20",
    "unidecode>=1.4.0",
]

[tool.uv.workspace]
members = [
    "LightRAG",
    "MinerU",
]

[tool.uv.sources]
lightrag-hku = { workspace = true }
mineru = { workspace = true }

[tool.pyright]
venvPath = "."
venv = ".venv"
executionEnvironments = [ {root = ".", extraPaths = ["LightRAG", "LangGraph", "VietnameseOcrCorrection"]} ]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "pypdf2>=3.0.1",
]
