seed_urls:
  - "https://daa.uit.edu.vn/quydinh-huongdan"
include_patterns:
  - "/quydinh-huongdan"
  - "/quytrinh"
  - "/huongdan"
  - "/vanban"
exclude_patterns:
  - "/tin-tuc"
max_depth: 3
concurrency: 2
rate_limit: 1
download_files: true
output_dir: "/data"
log_level: "INFO"
